{{- range $key, $value := .Values.customResource }}
apiVersion: {{ $value.apiVersion }}
kind: {{ $value.kind }}
metadata:
  name: {{ $key }}
  namespace: {{ $.Release.namespace }}
  labels:
{{- toYaml $value.labels | nindent 4 }}
{{- with $value.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
spec:
{{- toYaml $value.spec | nindent 2 }}
---


{{- end }}