{{- if and .Values.secret.enabled ( eq .Values.secret.isExternal false)  }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.secret.name }}"
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.labels" $ | nindent 4}}
    {{- range $key, $value := $.Values.secret.additionalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- if $.Values.secret.annotations }}
  annotations:
{{ toYaml $.Values.secret.annotations | indent 4 }}
{{- end }}
data:
{{- range $key,$value := .Values.secret.secrets}}
  {{ $key }}: {{ $value| b64enc }}
{{- end}}
{{- end }}


---

{{- if and .Values.secret.enabled  .Values.secret.isExternal }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.secret.name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    acme.org/owned-by: "{{ .Values.secret.serviceName }}"
spec:
  {{- with .Values.secret.secretStoreRef }}
  secretStoreRef:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  refreshInterval: "15m"
  target:
    name: "{{ .Values.secret.name }}"
  data:
    {{- range  .Values.secret.secretRefs }}
    - secretKey: {{ .local }}
      remoteRef:
        {{- if .remote }}
        key: {{ replace "." "" .remote }}
        {{- else }}
        key: {{ replace "." "" .local }}
        {{- end }}
    {{- end }}
{{- end }}

