{{- $root := . }}
{{- $serviceAccounts := list }}
{{- if .Values.serviceAccount | kindIs "map" }}
  {{- $serviceAccounts = append $serviceAccounts .Values.serviceAccount }}
{{- else if .Values.serviceAccount | kindIs "slice" }}
  {{- $serviceAccounts = .Values.serviceAccount }}
{{- else if .Values.security.serviceAccount | kindIs "map" }}
  {{- $serviceAccounts = append $serviceAccounts .Values.security.serviceAccount }}
{{- else if .Values.security.serviceAccount | kindIs "slice" }}
  {{- $serviceAccounts = .Values.security.serviceAccount }}
{{- end }}
{{- range $serviceAccounts }}
{{- if .create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name | default (include "common.serviceAccountName" $root) }}
  labels:
    {{- include "common.labels" $root | nindent 4 }}
    {{- range $key, $val := .labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
  {{- if .annotations }}
  annotations:
    {{- range $key, $val := .annotations }}
    {{ $key }}: {{ $val }}
    {{- end }}
    # ECR permissions for same account
    eks.amazonaws.com/role-arn: {{ .roleArn | default "arn:aws:iam::*:role/ECR-Pull-Role" }}
  {{- else }}
  annotations:
    # ECR permissions for same account
    eks.amazonaws.com/role-arn: {{ .roleArn | default "arn:aws:iam::*:role/ECR-Pull-Role" }}
  {{- end }}
automountServiceAccountToken: {{ .automountServiceAccountToken | default .automountToken | default false }}
---
{{- end }}
{{- end }}
