{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "helm-templates.fullname" . }}
  labels:
    {{- include "helm-templates.labels" . | nindent 4 }}
spec:
  {{- if .Values.job.parallelism }}
  parallelism: {{ .Values.job.parallelism }}
  {{- end }}
  {{- if .Values.job.completions }}
  completions: {{ .Values.job.completions }}
  {{- end }}
  {{- if .Values.job.backoffLimit }}
  backoffLimit: {{ .Values.job.backoffLimit }}
  {{- end }}
  {{- if .Values.job.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
  {{- end }}
  {{- if .Values.job.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "helm-templates.selectorLabels" . | nindent 8 }}
      {{- with .Values.job.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm-templates.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: {{ .Values.job.restartPolicy | default "OnFailure" }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.doppler.enabled }}
          envFrom:
            - secretRef:
                name: {{ include "helm-templates.fullname" . }}-doppler
          {{- end }}
          {{- if .Values.job.env }}
          env:
            {{- range $key, $value := .Values.job.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.job.command }}
          command:
            {{- toYaml .Values.job.command | nindent 12 }}
          {{- end }}
          {{- if .Values.job.args }}
          args:
            {{- toYaml .Values.job.args | nindent 12 }}
          {{- end }}
          {{- if .Values.job.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.job.volumeMounts | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.job.resources | nindent 12 }}
      {{- if .Values.job.volumes }}
      volumes:
        {{- toYaml .Values.job.volumes | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 