name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'universal/**'
      - '.github/workflows/publish-chart.yml'

env:
  CHART_NAME: universal
  GITHUB_PAGES_BRANCH: gh-pages
  GITHUB_REPO: jarakey/helm-templates

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to get all git tags

      - name: Set up Git
        run: |
          git config --global user.email "tolu@jarakey.com"
          git config --global user.name "jarakey-bot"

      - name: Bump chart version
        id: version
        run: |
          cd universal
          
          CURRENT_VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')
          echo "Current version: $CURRENT_VERSION"
          
          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
          patch=$((patch + 1))
          NEW_VERSION="${major}.${minor}.${patch}"
          
          sed -i "s/^version:.*/version: $NEW_VERSION/" Chart.yaml
          echo "New version: $NEW_VERSION"
          
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Lint and package chart
        run: |
          helm lint universal
          helm package -d universal universal
          cp universal/$CHART_NAME*.tgz .

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: universal

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Create Helm repository index
        run: |
          mkdir -p docs
          cp universal/$CHART_NAME*.tgz docs/
          helm repo index docs --url https://jarakey.github.io/helm-templates

      - name: Setup gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          git checkout main -- docs/
          git add docs/
          git commit -m "Publish Helm chart $CHART_NAME ${{ steps.version.outputs.new_version }}"
          git push origin gh-pages --force

      - name: Commit and push main branch changes
        run: |
          git checkout main
          git add universal/Chart.yaml
          git commit -m "Bump chart version to ${{ steps.version.outputs.new_version }}" || echo "No changes"
          git push origin main

      - name: Tag the release
        run: |
          git tag ${{ env.CHART_NAME }}-${{ steps.version.outputs.new_version }}
          git push origin ${{ env.CHART_NAME }}-${{ steps.version.outputs.new_version }}

      - name: Update repository description
        run: |
          echo "Helm chart published successfully!"
          echo "Chart: ${{ env.CHART_NAME }}"
          echo "Version: ${{ steps.version.outputs.new_version }}"
          echo "Repository URL: https://jarakey.github.io/helm-templates" 